### PR TITLE
Italy Compare PR for THANASIS

### PR DESCRIPTION
**Pull request by TheDetailedBread**
THANASIS

### CODE REVIEW

**Comment by Thanasis09** [comment]
fix loc, there is loc in more than one line, plus Victor Emmanuel is missing name loc

**Comment by Thanasis09** [comment]
@TheDetailedBread

**Review by Thanasis09 — CHANGES_REQUESTED** [review]
make the focus tree commented, push then uncomment, so at least ITA uses the generic one

**Review by Thanasis09 — COMMENTED** [review]
@TheDetailedBread

**Review by Thanasis09 — CHANGES_REQUESTED** [review]
what is `ITA_victor_emmanuel_iii_1`? if there needs to be 2 Victor Emmanuels add loc for that too

**Comment by TheDetailedBread** [comment]
alr

**Comment by Thanasis09** [comment]
If its ready ping me

**Review by Thanasis09 — APPROVED** [review]
.

**Comment by Thanasis09** [comment]
@TheDetailedBread if you think everything is ready. merge

**Pull request closed without merging**
