### PR TITLE
Brazil starting position

### PR DESCRIPTION
**Pull request by MateusTaffarel**

### CODE REVIEW

**Comment by Thanasis09** [comment]
branch is 5 commits behind
the result would be code overwritance

**Review by Thanasis09 — APPROVED** [review]
Seems good 👍

**Comment by MateusTaffarel** [comment]
yey

**Comment by Thanasis09** [comment]
@MateusT1044 merge when you want

**Comment by MateusTaffarel** [comment]
never did it, how?

**Pull request merged**
